version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recruting
      TZ: Asia/Almaty
    ports:
      - "5432:5432"
